In [2]:
mi = 0

In [3]:
# tfp.edward2

In [4]:
# import tensorflow_probability as tfp
# from tensorflow_probability import edward2 as ed
# ed.as_random_variable??

In [5]:
import pymisca.vis_util as pyvis
import pymisca.tensorflow_extra as pytf; reload(pytf)
import models as mym; reload(mym)
mi += 1
D = 2
m = mym.SunifLRP_VIMAP(name='test%d'%mi)
m.init_model(D=D,K=5,)

is in ipython: 1
is in ipython: 1
[WARN] pymisca.vis_util cannot find network


/home/shouldsee/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<class 'models.ModelA'> {'name': 'test'}
<models.ModelA object at 0x7fed3ddfe910> {'name': 'test'}
<class 'models.ModelA'> {'name': 'test'}
<models.ModelA object at 0x7fed3de75fd0> {'name': 'test'}
<class 'models.SunifLRP_VIMAP'> {'name': 'test1'}
None


In [6]:
import numpy as np

N = 5000
D = 6
K = scale = np.random.random(size=D)*3

x = (np.random.random(size=(D,1)) -0.5) * 8
K = np.diag(K) + x.T * x
K  = np.linalg.inv(K)
scale = K
# scale = (1., 2.5)

X1 = np.random.multivariate_normal((0,)*D, scale,size=5000)
#     X1 = X1/np.linalg.norm(X1,axis=1,keepdims=1)
X1 = X1.astype(np.float32)

pyvis.qc_2var(X1.T[0],X1.T[1])
pyvis.qc_2var(X1.T[1],X1.T[2])
pyvis.qc_2var(X1.T[0],X1.T[2])
data = X1

In [7]:
import sunif_vimap;reload(sunif_vimap)
_class = sunif_vimap.SunifLRP_VIMAP

In [26]:
import gamma_radial_affine_lrp; reload(gamma_radial_affine_lrp)
_class = gamma_radial_affine_lrp.GammaRadialAffineLRP_VIMAP

In [27]:
# %%pdb
mi += 1
ncomp = 2
# m = GammaRadialAffineLRP_VIMAP(name='test%d'%mi)
m = _class(name='test%d'%mi)
m.init_model(D=D,K=ncomp,)
# %pdb 1
m.fit(data,n_iter =0)

print (m.inference.loss.eval())

<class 'gamma_radial_affine_lrp.GammaRadialAffineLRP_VIMAP'> {'name': 'test5'}
('reuse', None)
('reuse', None)
hiModel
47996.246


In [12]:
??m.inference.initialize

In [12]:
m.inference.grads

[(<tf.Tensor 'gradients/test2_1/Softplus_2_grad/SoftplusGrad:0' shape=(1,) dtype=float32>,
  <tf.Variable 'test2/rate:0' shape=(1,) dtype=float32_ref>),
 (<tf.Tensor 'gradients/test2_1/Softplus_1_grad/SoftplusGrad:0' shape=(1,) dtype=float32>,
  <tf.Variable 'test2/concentration:0' shape=(1,) dtype=float32_ref>),
 (<tf.Tensor 'gradients/test2_1/Reshape_grad/Reshape:0' shape=(1,) dtype=float32>,
  <tf.Variable 'test2/q_pi:0' shape=(1,) dtype=float32_ref>)]

In [34]:
import edward.util as edu
m.prior.rate.get_children(),m.prior.concentration.get_children()

([<ed.RandomVariable 'Gamma_8/' shape=() dtype=float32>,
  <ed.RandomVariable 'Gamma_9/' shape=() dtype=float32>,
  <ed.RandomVariable 'inference_7/Mixture_7/' shape=(5000, 6) dtype=float32>,
  <ed.RandomVariable 'Mixture_7/' shape=(5000, 6) dtype=float32>],
 [<ed.RandomVariable 'Gamma_9/' shape=() dtype=float32>,
  <ed.RandomVariable 'Gamma_8/' shape=() dtype=float32>,
  <ed.RandomVariable 'inference_7/Mixture_7/' shape=(5000, 6) dtype=float32>,
  <ed.RandomVariable 'Mixture_7/' shape=(5000, 6) dtype=float32>])

In [28]:
[[x.eval() for x in y ] for y in m.inference.grads]
# m.inference.train.run()
# m.inference.build_loss_and_gradients??

[[array([0., 0.], dtype=float32),
  array([-1.0990103, -0.2532556], dtype=float32)],
 [array([0., 0.], dtype=float32),
  array([-0.04443014, -0.5364765 ], dtype=float32)],
 [array([ 3635.1821, -3635.1824], dtype=float32),
  array([ 1.009924  , -0.48970568], dtype=float32)]]

In [23]:
# m = _class(name='test%d'%mi)
# m.init_model(D=D,K=1,)
m.fit(data , n_iter = 3000,n_print=50)
m.inference.loss.eval()

hiModel
3000/3000 [100%] ██████████████████████████████ Elapsed: 4s | Loss: inf


inf

In [ ]:
a = m.components[0]
# a.sample(10)
# a.scale.shape
a.sample(10)

# a = m.x_post.components[0]
# a.log_prob(data)()
a.covariance().eval(),a.mean().eval()

a.log_prob(data).eval()

In [39]:
# m.x_post.
m.predict_proba(data,)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
# m.fit(data,n_iter =10)

# %pdb 0
m.predict(data)

In [ ]:
m.inference.loss.eval()

In [ ]:
m.paramDict

In [ ]:
m.param_key

In [ ]:
m.paramDict

In [ ]:
m.predict_proba(data)

In [ ]:
loss,gd = m.inference.build_loss_and_gradients(data)

In [ ]:
# gd[0][1]
m.inference.initialize()
m.inference.train
# loss.eval()

In [40]:
for k,v in m.post.__dict__.items():
    print(k,v.eval())

('loc', array([[ 3.9301969e-37, -5.4395678e-36, -1.1479374e-37, -2.8435444e-37,
        -3.2504891e-37, -3.0752748e-37]], dtype=float32))
('scale_perturb_factor', array([[[-0.02005112],
        [-0.7893711 ],
        [ 0.5368054 ],
        [ 0.50268054],
        [ 0.2682203 ],
        [-0.6365943 ]]], dtype=float32))
('scale_diag', array([[0.6313889 , 0.46837968, 0.3597648 , 1.1211302 , 1.0461136 ,
        0.42922184]], dtype=float32))
('weight', array([1.], dtype=float32))


In [41]:
for k,v in m.prior.__dict__.items():
    print(k,v.eval())

('loc', array([[-0.35587773, -1.5248173 ,  0.49760458,  1.6982158 ,  0.24277368,
         0.7816836 ]], dtype=float32))
('scale_perturb_factor', array([[[-59963.227],
        [ 63699.75 ],
        [ 95139.81 ],
        [-52482.82 ],
        [-83541.73 ],
        [-43157.004]]], dtype=float32))
('weight', array([1.], dtype=float32))
('scale_diag', array([[44582.926, 61496.83 , 15752.412, 25852.158, 47204.695, 37811.184]],
      dtype=float32))


In [ ]:
for k,v in m.post.__dict__.items():
    print(k,v.eval())

In [ ]:
m.post.weight.eval()

In [ ]:
# m.predict_proba(data)
m.postComponents[ 0 ].sample( 100).eval().shape

In [ ]:
m.x_post.sample(1).eval()